# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Infra Committee
tagline: The Infra committee maintains ACM@UIUC's infrastructure and engineering efforts.
description: The Infra committee maintains ACM@UIUC's infrastructure and engineering efforts.
author: Infra Committee
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://infra.acm.illinois.edu' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]
# logo: "/assets/images/acm-wordmark-light.png"

# Theme settings
remote_theme: acm-uiuc/sig-website-jekyll-theme@v0.13.0
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  "GitHub":
    - 'https://github.com/acm-uiuc'
footer_content:
nav_external_links:
  - title: Calendar
    url: https://acm.illinois.edu/calendar
  - title: Access Request Form
    url: https://forms.gle/3WqWP94u4sDtrAmx8
  - title: Public Infra Guides
    url: https://drive.google.com/drive/folders/1RfcVLbQ-T6HNiH98A8NuD-DWuk4jUK4h
  - title: Infra Team Documentation (auth required)
    url: https://drive.google.com/drive/folders/1n9yIDXcfQhXtkEN5qZTjIypibRkXYPdA

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: '/assets/images/'
      width: 300
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

liquid:
  error_mode: strict
  strict_filters: true

plugins:
  - jekyll-include-cache